app/convert/urls.py
from django.urls import path
from . import views

app_name = 'convert'
urlpatterns = [
    path('', views.LengthView.as_view(), name='root'),
    path('length', views.LengthView.as_view(), name='length'),
    path('weight', views.WeightView.as_view(), name='weight'),
    path('temperature', views.TemperatureView.as_view(), name='temperature'),
]

app/unitconverter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('convert/', include('convert.urls'))
]

app/convert/models.py
# from django.db import models

# Create your models here.

app/convert/views.py
from django.shortcuts import render
from django.views import View

from enum import Enum
from typing import List, Dict, Optional


def get_str_units_list(enum_class) -> List[str]:
    return [unit.name.lower() for unit in enum_class]


def get_str_units_map(enum_class) -> Dict[str, Enum]:
    return {unit.name.lower(): unit for unit in enum_class}


def get_result(enum_map, get_params, converter, ctx) -> Optional[float]:
    got_units = True
    from_unit = None
    to_unit = None
    units_in_dict = ("from_unit" in get_params and "to_unit" in get_params)
    try:
        from_unit, to_unit = \
            enum_map[get_params["from_unit"]], \
            enum_map[get_params["to_unit"]]
    except Exception:
        if units_in_dict:
            ctx["error_msg"] = "Invalid units!"
        got_units = False

    got_value = True
    value_in_dict = False
    if "input_value" in get_params:
        value_in_dict = True
    input_value = 0.0
    try:
        input_value = float(get_params["input_value"])
    except Exception:
        if value_in_dict:
            ctx["error_msg"] = "Invalid input value"
        got_value = False

    if got_units and from_unit is not None and to_unit is not None:
        ctx["from_unit"], ctx["to_unit"] = from_unit.name.lower(), \
                to_unit.name.lower()
    if got_value:
        ctx["input_value"] = str(input_value)

    return converter(from_unit, to_unit, input_value) \
        if got_value and got_units else None


class LengthUnits(Enum):
    Millimeter = 1.0
    Centimeter = Millimeter / 10.0
    Meter = Centimeter / 100.0
    Kilometer = Meter / 1000.0
    Inch = Millimeter / 25.4
    Foot = Inch / 12.0
    Yard = Foot / 3.0
    Mile = Yard / 1760.0

    @staticmethod
    def convert(src: "LengthUnits", dest: "LengthUnits",
                value: float) -> float:
        return (value / src.value) * dest.value


class LengthView(View):
    template_name = "convert/convert.html"
    convert_type = "length"
    units = get_str_units_list(LengthUnits)
    units_map = get_str_units_map(LengthUnits)

    def get(self, request):
        ctx = {"units": self.units,
               "convert_type": self.convert_type,
               }

        result = get_result(self.units_map,
                            request.GET,
                            LengthUnits.convert, ctx)
        if result is not None:
            ctx["result"] = str(result)

        return render(request,
                      self.template_name,
                      ctx)


class WeightUnits(Enum):
    Milligram = 1.0
    Gram = Milligram / 1000.0
    Kilogram = Gram / 1000.0
    Ounce = Milligram / 28349.5
    Pound = Ounce / 16.0

    @staticmethod
    def convert(src: "WeightUnits", dest: "WeightUnits",
                value: float) -> float:
        return (value / src.value) * dest.value


class WeightView(View):
    template_name = "convert/convert.html"
    convert_type = "weight"
    units = get_str_units_list(WeightUnits)
    units_map = get_str_units_map(WeightUnits)

    def get(self, request):
        ctx = {"units": self.units,
               "convert_type": self.convert_type,
               }
        result = get_result(self.units_map,
                            request.GET,
                            WeightUnits.convert, ctx)
        if result is not None:
            ctx["result"] = str(result)
        return render(request,
                      self.template_name,
                      ctx)


class TemperatureUnits(Enum):
    Celsius = 1
    Fahrenheit = 2
    Kelvin = 3

    @staticmethod
    def convert(src: "TemperatureUnits", dest: "TemperatureUnits",
                value: float) -> float:
        if src == dest:
            return value
        tu = TemperatureUnits
        if src == tu.Celsius:
            if dest == tu.Fahrenheit:
                return (value * 9.0 / 5.0) + 32.0
            else:  # dest == tu.Kelvin
                return value + 273.15
        elif src == tu.Fahrenheit:
            if dest == tu.Celsius:
                return (value - 32) * 5.0 / 9.0
            else:  # dest == tu.Kelvin
                return ((value - 32) * 5.0 / 9.0) + 273.15
        else:
            if dest == tu.Celsius:
                return value - 273.15
            else:  # dest == tu.Fahrenheit
                return ((value - 273.15) * 9.0 / 5.0) + 32.0


class TemperatureView(View):
    template_name = "convert/convert.html"
    convert_type = "temperature"
    units = get_str_units_list(TemperatureUnits)
    units_map = get_str_units_map(TemperatureUnits)
    unit_set = set(units)

    def get(self, request):
        ctx = {"units": self.units,
               "convert_type": self.convert_type,
               }
        result = get_result(self.units_map,
                            request.GET,
                            TemperatureUnits.convert, ctx)
        if result is not None:
            ctx["result"] = str(result)
        return render(request,
                      self.template_name,
                      ctx)

app/convert/templates/convert/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Unit Converter</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'convert/favicon.ico' %}"/>
        <link rel="icon" href="./favicon.ico" type="image/x-icon">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'convert/styles.css' %}">
    </head>
    <body>
        <main>
            <div>
                <h1>Unit Converter</h1>
                {% block navbar %}
                {% endblock %}
                {% block content %}
                {% endblock %}
            </div>
        </main>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

app/convert/templates/convert/convert.html
{% extends "convert/base.html" %}
{% load static %}

{% block navbar %}
{% include "convert/navbar.html" %}
{% endblock %}

{% block content %}
{% if result %}
<div>
    <br>
    <h3>Result of your calculation</h3>
    <br>
    <p>
        <strong>{{input_value}}</strong>
        <em> {{from_unit|capfirst}}</em> =
        <strong> {{result|floatformat:2}}</strong>
        <em> {{to_unit|capfirst}}</em>
    </p>
    <br>
    {% if convert_type == "length" %}
    <button class="btn btn-danger" onclick="window.location='{% url 'convert:length' %}'"
        type="button">Reset</button>
    {% elif convert_type == "weight" %}
    <button class="btn btn-danger" onclick="window.location='{% url 'convert:weight' %}'"
        type="button">Reset</button>
    {% else %}
    <button class="btn btn-danger" onclick="window.location='{% url 'convert:temperature' %}'"
        type="button">Reset</button>
    {% endif %}
</div>
{% else %}
<div>
    <div>
        {% if error_msg %}
        <div class="alert alert-danger" role="alert">{{error_msg}}</div>
        {% endif %}
    </div>
    <form action="" method="get" id="unit_form">
        {% csrf_token %}
        <div class="form-group">
            <label for="input_value">
                Enter the {{convert_type | lower}} to convert
            </label><br>
            <input class="form-control"
                type="number" id="input_value" step="any"
                name="input_value" required>
        </div>
        <br>

        <div class="form-group">
            <label for="from_unit">Unit to convert from</label>
            <br>
            <select class="form-control"
                id="from_unit" name="from_unit">
                {% for unit in units %}
                <option value="{{unit}}">{{unit | capfirst}}</option>
                {% endfor %}
            </select>
        </div>
        <br>

        <div class="form-group">
            <label for="to_unit">Unit to convert to</label>
            <select class="form-control"
                id="to_unit" name="to_unit">
                {% for unit in units %}
                <option value="{{unit}}">{{unit | capfirst}}</option>
                {% endfor %}
            </select>
        </div>
        <br>
        <button class="btn btn-success" type="button"
            onclick="swap_units()">Swap units</button>
        <br>
        <br>

        <input class="btn btn-primary" type="submit" value="Convert">
        <input class="btn btn-danger" type="reset" value="Reset">
    </form>
</div>
{% endif %}
{% endblock %}

{% block scripts %}
<script src="{% static 'convert/units.js' %}"></script>
<script>

function select_in_navbar() {
    let ul = document.getElementById('navul');
    let items = ul.getElementsByTagName('li');
    for (let idx = 0; idx < items.length; ++idx) {
        const item = items[idx];
        const content = item.innerText.toLowerCase();
        if (content == '{{convert_type}}') {
            item.classList.add('selected-item');
        } else {
            item.classList.remove('selected-item');
        }
    }
}
select_in_navbar();
</script>
{% endblock %}

app/convert/templates/convert/navbar.html
<nav>
    <ul id="navul" class="dfnavbar">
        <li class="dfnavbar">
            <a href="{% url 'convert:length' %}">Length</a>
        </li>
        <li class="dfnavbar">
            <a href="{% url 'convert:weight' %}">Weight</a>
        </li>
        <li class="dfnavbar">
            <a href="{% url 'convert:temperature' %}">
                Temperature</a>
        </li>
    </ul>
</nav>